# Generated by Django 3.2 on 2022-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contnant',
        ),
        migrations.AddField(
            model_name='post',
            name='contnent',
            field=models.TextField(default='', max_length=5000, verbose_name='contant'),
        ),
    ]
