# Generated by Django 3.2 on 2022-08-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220829_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contnent',
            field=models.TextField(max_length=5000, verbose_name='contant'),
        ),
    ]
